__author__ = 'YangZiyue, ShanYongtao'
__author_email__ = 'yangzy58@mail2.sysu.edu.cn'
__description__ = 'A Comprehensive Platform for Discovering and Characterizing RNA Viruses in Depth.'
__license__ = 'MIT'
__name__ = 'VirID'
__python_requires__ = '==3.8'
__status__ = 'Production'
__title__ = 'VirID'
__url__ = 'https://github.com/ZiyueYang01/VirID'
__version__ = '3.1.0'
